---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitor

configMapGenerator:
  - name: prometheus-kube-config
    files:
      - conf/prom-kube/prometheus.yml


resources:
  - prometheus-rbac.yaml
  - prometheus-secgroup.yaml
  - prometheus-kube.yaml
