---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-kube
  labels:
    app.kubernetes.io/name: prometheus-kube
    app.kubernetes.io/component: prometheus
    app: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-kube
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-kube
        app.kubernetes.io/component: prometheus
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest # <--- :latest may be dangerous.
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention=30d"
          volumeMounts:
            - name: data
              subPath: prometheus
              mountPath: /prometheus
            - name: config
              subPath: prometheus.yml
              mountPath: /etc/prometheus/prometheus.yml
          ports:
            - containerPort: 9090
              protocol: TCP
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-kube
        - name: config
          configMap:
            name: prometheus-kube-config
      serviceAccountName: prometheus
      securityContext:
        runAsUser: 5001
        runAsGroup: 5001
        fsGroup: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube
spec:
  selector:
    app.kubernetes.io/name: prometheus-kube
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube
  labels:
    app.kubernetes.io/name: prometheus-kube
    app.kubernetes.io/component: prometheus
    vol: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8G
  storageClassName: local-path
